FROM rust:1.96 as builder
WORKDIR /app
COPY Cargo.toml Cargo.lock* ./
COPY common ./common
COPY domain ./domain
COPY db ./db
COPY outbox ./outbox
COPY worker ./worker
COPY scheduler ./scheduler
COPY api ./api
RUN cargo build --release -p worker

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/worker /usr/local/bin/worker
CMD ["worker"]
